version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: labdasa
      MYSQL_USER: labdasa
      MYSQL_PASSWORD: labdasa
      MYSQL_ROOT_PASSWORD: labdasa
    volumes:
      - /tmp/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: labdasa
      MYSQL_PASSWORD: labdasa
      MYSQL_ROOT_PASSWORD: labdasa